import Head from "next/head"
import NFTGallery from "@/components/NFTGallery"
import {fetchNFT} from "@/services";

export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Jack&apos;s zkBNB NFT</h1>
        <NFTGallery {...props} />
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  try {
      console.log("Getting NFTs...")

      const nfts = await fetchNFT()
      const props = JSON.stringify(nfts)

      return {
          props: {
              props
          },
          revalidate: 3600
      };
  } catch (err) {
      console.error('page error', err)
      // we don't want to publish the error version of this page, so
      // let next.js know explicitly that incremental SSG failed
      throw err
  }
}
